#' Calculate OOB proximity from ranger random forest model
#'
#' Given an existing random forest model generated by the ranger package,
#' calculate the proximity between each pair of features in the original model.
#' This is only calculated using trees where _both_ samples are out-of-bag to
#' avoid overly optimistic proximity measures.
#'
#' Code adapted from \url{https://github.com/imbs-hl/ranger/issues/234}
#'
#' @param rf_fit a ranger model
#' @param old_data The data used to fit the original model
#'
#' @return A symmetric matrix containing the proximity values.
#'
#' @export
extract_proximity_oob = function(rf_fit, old_data) {
  pred = stats::predict(rf_fit, old_data, type = "terminalNodes")$predictions
  prox = matrix(NA, nrow(pred), nrow(pred))
  ntree = ncol(pred)
  n = nrow(prox)

  if (is.null(rf_fit$inbag.counts)) {
    stop("call ranger with keep.inbag = TRUE")
  }

  # Get inbag counts
  inbag = simplify2array(rf_fit$inbag.counts)

  for (i in 1:n) {
    for (j in 1:n) {
      if(i == j) {
        # self, so prox == 1
        prox[i, j] <- 1
      } else if(j < i) {
        # we are below the diagonal, we can copy down the already computed similarity
        prox[i, j] <- prox[j, i]
      } else {
        # Use only trees where both obs are OOB
        tree_idx = inbag[i, ] == 0 & inbag[j, ] == 0
        prox[i, j] = sum(pred[i, tree_idx] == pred[j, tree_idx]) / sum(tree_idx)
      }
    }
  }

  return(prox)
}
