# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findMatchesC <- function(feature_rts, drt_max) {
    .Call('_jrtools_findMatchesC', PACKAGE = 'jrtools', feature_rts, drt_max)
}

