#' Read MSP files from MoNA spectral library
#'
#' Parses the flavor of MSP file generated by the MassBank of North America
#' (MoNA) spectral library. This parser also handles MSP files generated by the
#' GNPS spectral library.
#'
#' @param path The location of the MSP file to import
#'
#' @return A list of entries where each entry has the header information as a
#'   list of key-value pairs and the spectrum itself as a matrix with m/z and
#'   intensity columns.
#'
#' @export
read_mona_msp <- function(path) {
  all_spectra <- list()
  spec_idx <- 1

  # open file
  fd <- file(path, "r", blocking = TRUE)

  # read first line
  f_line <- readLines(fd, n = 1)
  # while there are more lines
  while(length(f_line) > 0) {
    spec_hdr <- list()

    # read header lines, stopping at blank line or 'Num Peaks' key
    while(length(f_line) > 0 && nchar(f_line) > 0 && stringr::str_starts(f_line, stringr::coll("Num Peaks:"), negate = TRUE)) {
      # split into key/value
      kv <- stringr::str_match(f_line, "^(.+?):\\s*(.+)$")
      # warn on duplicate header keys
      if(utils::hasName(spec_hdr, kv[2])) {
        # warning(paste0("Feature #", spec_idx, ": detected duplicate header key `", kv[2], "` in line\n`",
        #                f_line, "`"))
        spec_hdr[[kv[2]]] <- append(spec_hdr[[kv[2]]], kv[3])
      } else {
        # add to header
        spec_hdr[kv[2]] <- kv[3]
      }

      # read next line
      f_line <- readLines(fd, n = 1)
    }

    # if we've hit premature end-of-file
    if(length(f_line) == 0) {
      warning("Encountered unexpected end-of-file! Last entry is likely malformed!")
      # add header only and return
      all_spectra[[spec_idx]] <- list("header" = spec_hdr, "spectrum" = NA)
      # close connection
      close(fd)
      return(all_spectra)
    }

    # sometimes we encounter headers with no spectrum
    if(nchar(f_line) == 0) {
      spec_hdr["Num Peaks"] <- 0

      blank_spectrum <- matrix(data = NA_real_, nrow = 0, ncol = 2)
      colnames(blank_spectrum) <- c("mz", "intensity")

      # add header and empty spectrum to list
      all_spectra[[spec_idx]] <- list("header" = spec_hdr, "spectrum" = blank_spectrum)
    } else { # we have a proper spectrum to read
      # how many peaks in this spectrum?
      n_peaks <- as.integer(substr(f_line, 11, nchar(f_line)))
      spec_hdr["Num Peaks"] <- n_peaks

      # read all peaks at once
      peak_table <- stringr::str_split(stringr::str_trim(readLines(fd, n_peaks), side = "both"), "\\s", simplify = TRUE)
      # convert to numeric
      class(peak_table) <- "numeric"
      # add column names
      colnames(peak_table) <- c("mz", "intensity")

      # add header and spectrum to list
      all_spectra[[spec_idx]] <- list("header" = spec_hdr, "spectrum" = peak_table)

      # if we hit end of file, return data with warning
      if(nrow(peak_table) < n_peaks) {
        warning(paste0("Encountered unexpected end-of-file! Expected ", n_peaks,
                       " peaks, but only found ", nrow(peak_table), "!\n",
                       "Last entry is missing data!"))
        # close connection
        close(fd)
        return(all_spectra)
      }
    }

    # read blank lines between entries
    f_line <- readLines(fd, n = 1)
    # not end of file
    if(length(f_line) > 0) {
      # while lines are blank
      is_blank <- nchar(f_line) == 0
      while(is_blank) {
        f_line <- readLines(fd, n = 1)
        # end of file isn't blank line
        if(length(f_line) == 0) {
          is_blank <- FALSE
        } else {
          is_blank <- nchar(f_line) == 0
        }
      }
    }
    spec_idx <- spec_idx + 1
  }
  # close file connection
  close(fd)

  return(all_spectra)
}
