#' Read MGF files from the GNPS spectral library
#'
#' Parses the flavor of MGF file generated by the GNPS
#' spectral library.
#'
#' @param path The location of the MGF file to import
#'
#' @return A list of entries where each entry has the header information as a
#'   list of key-value pairs and the spectrum itself as a matrix with m/z and
#'   intensity columns.
#'
#' @export
read_mgf <- function(path) {
  # open file
  fd <- file(path, "r", blocking = TRUE)
  # read the whole thing at once
  all_lines <- readLines(fd)
  # close it again
  close(fd)

  # find starts of all spectra
  spec_start_idx <- which(all_lines == "BEGIN IONS")
  # find ends of all spectra
  spec_end_idx <- which(all_lines == "END IONS")

  # how many spectra?
  n_spectra <- length(spec_start_idx)
  # allocate list for spectra
  all_spectra <- vector(mode = "list", length = n_spectra)

  # find all header lines
  all_hdr_idx <- regexpr("=", all_lines, fixed = TRUE) - 1
  # which lines are headers?
  is_hdr <- all_hdr_idx > 0

  for(i in seq_along(all_spectra)) {
    idx1 <- spec_start_idx[i] + 1
    idx2 <- spec_end_idx[i] - 1

    # pull header keys
    hdr_idx <- which(is_hdr[idx1:idx2]) + idx1 - 1
    hdr_keys <- substr(all_lines[hdr_idx], start = 1, stop = all_hdr_idx[hdr_idx])
    # pull header values
    hdr_values <- substr(all_lines[hdr_idx], start = all_hdr_idx[hdr_idx] + 2,
                         stop = nchar(all_lines[hdr_idx]))
    # make header list
    spec_hdr <- as.list(hdr_values)
    names(spec_hdr) <- hdr_keys

    # extract peaks
    pk_idx <- which(!is_hdr[idx1:idx2]) + idx1 - 1
    if(length(pk_idx) > 0) {
      pks <- strsplit(all_lines[pk_idx], " ", fixed = TRUE)
      pks <- do.call(rbind, pks)
      class(pks) <- "numeric"
      colnames(pks) <- c("mz", "intensity")
    } else {
      pks <- NA
    }

    # put into list
    all_spectra[[i]] <- list("header" = spec_hdr, "spectrum" = pks)
  }
  return(all_spectra)
}
